# Generated by Django 4.1.7 on 2023-04-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.IntegerField(max_length=10)),
                ('Email', models.EmailField(max_length=100)),
                ('Mobile_no', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='contactdata',
        ),
    ]
